// const app = express.app();
//
// app.get("/", controler.homePage);
// app.get("/index", controler.homePage);
// app.post("/login", controler.login);
// app.post("/upPost", controler.addPost);
// app.get("/newsPost", controler.newsPost);
// app.get("/notiPost", controler.notiPost);
// app.get("/eventPost", controler.eventPost);
// app.get("/getNewsTotal", controler.getNewsTotal);
// app.get("/aboutUs", controler.aboutUs);
// app.get("/priceTable", controler.priceTable);
// app.get("/shareServices", controler.shareServices);
// app.get("/shareServicesTrans", controler.shareServicesTrans);
// app.get("/shareServicesFinaceCor", controler.shareServicesFinaceCor);
// app.get("/shareServicesFamily", controler.shareServicesFamily);
// app.get("/shareServicesFinaceBanking", controler.shareServicesFinaceBanking);
// app.get("/shareServicesTax", controler.shareServicesTax);
// app.get("/shareServicesSupport", controler.shareServicesSupport);
// app.get("/course", controler.course);
// app.get("/hireEmp", controler.hireEmp);
// app.get("/contactUs", controler.contactUs);
//
// export default app;

var controler = require("./controllers/econsultControllers");

module.exports = function (app) {
    app.get("/", controler.homePage);
    app.get("/index", controler.homePage);
    app.post("/login", controler.login);
    app.post("/upPost", controler.addPost);
    app.post("/deletePost", controler.deletePost);
    app.post("/sendContact", controler.sendContact);
    app.get("/newsPost", controler.newsPost);
    app.get("/notiPost", controler.notiPost);
    app.get("/eventPost", controler.eventPost);
    app.get("/getNewsTotal", controler.getNewsTotal);
    app.get("/aboutUs", controler.aboutUs);
    app.get("/priceTable", controler.priceTable);
    app.get("/shareServices", controler.shareServices);
    app.get("/shareServicesTrans", controler.shareServicesTrans);
    app.get("/shareServicesFinaceCor", controler.shareServicesFinaceCor);
    app.get("/shareServicesFamily", controler.shareServicesFamily);
    app.get("/shareServicesFinaceBanking", controler.shareServicesFinaceBanking);
    app.get("/shareServicesTax", controler.shareServicesTax);
    app.get("/shareServicesSupport", controler.shareServicesSupport);
    app.get("/course", controler.course);
    app.get("/hireEmp", controler.hireEmp);
    app.get("/contactUs", controler.contactUs);
    app.get("/reUp", controler.reUp);
    app.get("/newestPostToEdit", controler.newestPostToEdit);
    app.post("/editPost", controler.editPost);
    app.post("/updatePost", controler.updatePost);
    app.get("/detailPage", controler.detailPage);
    app.get("/newestNewsPost", controler.newestNewsPost);
    app.get("/newestNewsNotice", controler.newestNewsNotice);
    app.get("/newestNewsEvent", controler.newestNewsEvent);
    app.get("/newestNewsService", controler.newestNewsService);
    app.get("/newestNewsCourse", controler.newestNewsCourse);
    app.get("/course1", controler.course1);
    app.get("/course2", controler.course2);
    app.get("/course3", controler.course3);
    app.get("/course4", controler.course4);
    app.get("/course5", controler.course5);
    app.get("/course6", controler.course6);
    app.get("/course7", controler.course7);
    app.get("/course8", controler.course8);
    app.get("/course9", controler.course9);
    app.get("/course10", controler.course10);
    app.get("/course11", controler.course11);
    app.get("/course12", controler.course12);
    app.get("/course13", controler.course13);
}